version: "2"
services:
  proxy:
      build: .
      entrypoint: sbt run
      image: conbrad/redisproxy:latest
      environment:
          - EXPIRY_TIME=1000
          - CAPACITY=1000
      ports:
          - "9000:9000"
      depends_on:
        - redis
      links:
          - redis
      tty: true
  proxy-test:
        build: .
        entrypoint: sbt test
        image: conbrad/redisproxy:latest
        tty: true
  redis:
      image: redis
      volumes:
       - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      entrypoint: redis-server /usr/local/etc/redis/redis.conf
      ports:
          - "6379:6379"