version: "2"
services:
  proxy:
      build: .
      entrypoint: sbt "run $PROXY_PORT"
      image: conbrad/redisproxy:latest
      environment:
          - EXPIRY_TIME=10000
          - CAPACITY=1000
          - PROXY_PORT=9000
          - REDIS_ADDR=redis
          - PROTOCOL_HOST=127.0.0.1
          - PROTOCOL_PORT=9002
      ports:
          - "9000:9000"
      depends_on:
        - redis
      links:
          - redis
      tty: true
  proxy-test:
        build: .
        entrypoint: sbt test
        image: conbrad/redisproxy:latest
        tty: true
  redis:
      image: redis
      volumes:
       - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      entrypoint: redis-server /usr/local/etc/redis/redis.conf
      ports:
          - "6379:6379"